# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: iOS Real Device
    init: cd gitpod/ # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: bash ./xcuitest-real.sh
